[build]

base = "_site"

publish = "./public"

command = "gulp qa"

[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true


