[build]

base = "/"

publish = "/"

command = "npm run build:prod"

[context.production]
    publish = "/"
    NODE_ENV = "production"
    command = "npm run build:scss"

[context.deploy-preview]
    publish = "/"
    NODE_ENV = "dev"
    command = "npm run build:scss"

[context.staging]
    NODE_ENV = "test"
    command = "npm run build:scss"
    base = "staging"

[context."feat/branch"]
    NODE_ENV = "feat"
    command = "npm run build:scss"
    base = "branch"


